name: Release App
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
    
on:
  push:
     branches: [ main ]
     
jobs:
 retrievingVersion:
  runs-on: ubuntu-latest
  outputs:
      version: ${{ steps.versionstep.outputs.version }}
      previousTag: ${{ steps.previousTag.outputs.previousTag }}
  steps:
    - uses: actions/checkout@v3
      with: 
        fetch-tags: true
        fetch-depth: 0
    - name: Retrieve Release Version
      id: versionstep
      working-directory: jackbox_patcher
      run: |
         VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
         echo "version=${VERSION}" >> $GITHUB_OUTPUT
         echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Get previous tag
      id: previousTag
      run: |
        echo "$(git --no-pager tag --sort=creatordate --merged main | grep -v beta)"
        name=$(git --no-pager tag --sort=creatordate --merged main | grep -v beta | tail -1 | head -1)
        echo "previousTag: $name"
        echo "previousTag=$name" >> $GITHUB_ENV
        echo "previousTag=$name" >> $GITHUB_OUTPUT
    - uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: ${{ env.VERSION }}
        message: "Release ${{ env.VERSION }}"
        tag_exists_error: "false"
        no_verify_tag: "true"
    
 build_windows:
   runs-on: windows-latest
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.35.1'
        channel: 'stable'
     - name: Build windows
       working-directory: ./jackbox_patcher
       run: flutter build windows --build-name ${{ needs.retrievingVersion.outputs.version }} -t ./lib/main_release.dart
     - name: Build media_kit_remover tool
       working-directory: ./tools/media_kit_remover
       run: |
        mkdir ../../jackbox_patcher/build/windows/x64/runner/Release/tools/
        dart compile exe --target-os windows ./bin/media_kit_remover.dart -o ../../jackbox_patcher/build/windows/x64/runner/Release/tools/media_kit_remover.exe
     - name: Add windows dlls
       working-directory: .
       run: |
        copy .\libs\windows\* .\jackbox_patcher\build\windows\x64\runner\Release\
     - uses: actions/upload-artifact@v4
       with:
          name: build_windows
          path: ./jackbox_patcher/build/windows/x64/runner/Release
          
 build_linux:
   runs-on: ubuntu-24.04 
   needs: retrievingVersion
   steps:
     - uses: actions/checkout@v3
     - run: |
        sudo apt-get update -y
        sudo apt install libmpv-dev mpv
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
        sudo apt-get install fuse libfuse2
        sudo apt-get install curl libcurl4-openssl-dev
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.35.1'
        channel: 'stable'
     - name: Remove media_kit_libs for linux
       working-directory: ./jackbox_patcher
       run: |
        mv ./pubspec.yaml pubspec_old.yaml
        cat ./pubspec_old.yaml | grep -v media_kit_libs > ./pubspec.yaml
     - name: Build linux
       working-directory: ./jackbox_patcher
       run: flutter build linux --build-name ${{ needs.retrievingVersion.outputs.version }} -t ./lib/main_release.dart
     - uses: actions/upload-artifact@v4
       with:
          name: build_linux
          path: ./jackbox_patcher/build/linux/x64/release/bundle
 upload:
    runs-on: ubuntu-latest
    needs: 
      - build_windows
      - build_linux
      - retrievingVersion
    steps: 
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ needs.retrievingVersion.outputs.version }}
          toTag: ${{ needs.retrievingVersion.outputs.previousTag }}
      - run: mkdir -p dist
      - uses: actions/download-artifact@v4
        with:
          name: build_windows
          path: dist/JackboxUtility_Windows
      - uses: actions/download-artifact@v4
        with:
          name: build_linux
          path: dist/JackboxUtility_Linux
      - name: Zipping windows release
        working-directory: dist/JackboxUtility_Windows
        run: |
          zip -r ../../JackboxUtility_Windows.zip *
      - name: Zipping linux release
        working-directory: dist/JackboxUtility_Linux
        run: |
          zip -r ../../JackboxUtility_Linux.zip *
      - name: Upload release onto Github
        uses: ncipollo/release-action@v1
        with:
         artifacts: 'JackboxUtility_Windows.zip,JackboxUtility_Linux.zip'
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ needs.retrievingVersion.outputs.version }}
         body: ${{ steps.changelog.outputs.changes }}
         prerelease: false
         allowUpdates: true
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: dev
          commit_message: 'docs: update CHANGELOG.md for ${{ needs.retrievingVersion.outputs.version }} [skip ci]'
          file_pattern: CHANGELOG.md
  
